### ISSUE TITLE
kouj10 - neodevzdané zadání

### ISSUE THREAD

**Issue by Hoko99** [nvbach91/4IZ268-2021-2022-ZS#112]
Dobrý den,

omlouvám se za neodevzdané zadání. Nevím, co se stalo, jsem si skoro jistý, že jsem zadání odevzdával.

Zde je soubor s uloženými odpověďmi:
[4IZ268 Návrh projektu - single page aplikace.pdf](https://github.com/nvbach91/4IZ268-2021-2022-ZS/files/7757874/4IZ268.Navrh.projektu.-.single.page.aplikace.pdf)

a wireframe:
![wireframe](https://user-images.githubusercontent.com/77194583/146990674-da9f9c67-8794-4a23-87d3-56f0b9db8d94.png)

**Comment by nvbach91** [comment]
@Hoko99 návrh je ok, kdyžtak to dopošlete znova přes formulář, stačí screenshoty, ať nemusíte opisovat
