### ISSUE TITLE
kons04 - neodevzdaný návrh SP2

### ISSUE THREAD

**Issue by EttKon** [nvbach91/4IZ268-2021-2022-ZS#157]
Dobrý den, 
překvapilo mě, že jsem neodevzdal návrh na SP2, pravděpodobně jsem nekliknul na submit, vyplnil jsem formulář znovu a odevzdal návrh. Dále z mě neznámého důvodu nemám push acces do repositáře pro odevzdávání. Prosím o opětovné zaslání linku, v mailu ho nemohu najít.

**Comment by nvbach91** [comment]
https://github.com/nvbach91/4IZ268-2021-2022-ZS/issues/1
