### ISSUE TITLE
Změna použitých technologií v návrhu SP2

### ISSUE THREAD

**Issue by jirkavrba** [nvbach91/4IZ268-2021-2022-ZS#53]
Dobrý den,
rád bych ještě upravil použité technologie a vlastně tím pádem i API ve svém návrhu semestrální práce 2.

Místo phoenix + liveview bych použil vlastní "klasické" HTTP API + socket.io server a pro client code bych použil následující knihovny:
- vue.js (https://vuejs.org/v2/
- vue-router (https://router.vuejs.org)
- vuex (https://vuex.vuejs.org)
- tailwindcss (https://tailwindcss.com)
- socket.io (https://socket.io/)

**Comment by nvbach91** [comment]
@jirkavrba ještě jste neodevzdal návrh ne?

**Comment by jirkavrba** [comment]
Nepotvrdil jsem tam odeslání, pardon, pošlu rovnou s upravenými technologiemi :+1:

**Comment by nvbach91** [comment]
SP2 je víceméně freestyle takže používejte cokoliv, budu hodnotit pouze klientskou část, aby tam byly věci jako AJAX, Promise, DOM, API, Search, Input validation, ...

viz https://github.com/nvbach91/4IZ268-2021-2022-ZS/wiki/Pokyny-SP2
