### ISSUE TITLE
HW01

### ISSUE THREAD

**Issue by nvbach91** [nvbach91/4IZ268-2021-2022-ZS#6]

**Comment by lukas-vit** [comment]
Dobrý den,
odevzdávám úkol z prvního cvičení.
Odkaz: https://eso.vse.cz/~vitl03/cv01/

**Comment by 637man** [comment]
Odevzdávám úkol z 1. cvičení, který je v materiálech na 2. cvičení.

[](https://eso.vse.cz/~getj00/cv02/)
[](https://eso.vse.cz/~getj00/cv02/blog/)
[](https://eso.vse.cz/~getj00/cv02/cheatsheet/)
[](https://eso.vse.cz/~getj00/cv02/resume/)

Je vidět, že tomu chybí CSS.

**Comment by jirkavrba** [comment]
Také odevzdávám úkol z 1. cvičení
- [https://eso.vse.cz/~vrbj04/hw01/](https://eso.vse.cz/~vrbj04/hw01/index.html)
- [https://eso.vse.cz/~vrbj04/hw01/cheatsheet](https://eso.vse.cz/~vrbj04/hw01/cheatsheet/index.html)
- [https://eso.vse.cz/~vrbj04/hw01/blog](https://eso.vse.cz/~vrbj04/hw01/blog/index.html)
- [https://eso.vse.cz/~vrbj04/hw01/resume](https://eso.vse.cz/~vrbj04/hw01/resume/index.html)

**Comment by AirbornBird88** [comment]
Dobrý den, 
přikládám odkazy na stránky s domácím úkolem:
🍡 
1. [Domovská stránka](https://eso.vse.cz/~doho01/cv02/)
2. [Cheatsheet](https://eso.vse.cz/~doho01/cv02/cheatsheet/)
3. [Blog](https://eso.vse.cz/~doho01/cv02/blog/)
4. [Resume](https://eso.vse.cz/~doho01/cv02/resume/)

**Comment by sarajuliefrajtova** [comment]
Dobrý den, 
odevzdám úkol z 1. cvičení:

- [Domovská stránka](https://eso.vse.cz/~fras07/cv02/)
- [Tahák](https://eso.vse.cz/~fras07/cv02/cheatsheet/)
- [Blog](https://eso.vse.cz/~fras07/cv02/blog/)
- [Životopis](https://eso.vse.cz/~fras07/cv02/resume/)

**Comment by jochimv** [comment]
Dobrý den,
odevzdávám úkol z prvního cvičení.

- [navigace](https://eso.vse.cz/~jocv00/cv02/index.html)
- [blog](https://eso.vse.cz/~jocv00/cv02/blog/index.html)
- [cheatsheet](https://eso.vse.cz/~jocv00/cv02/cheatsheet/index.html)
- [resume](https://eso.vse.cz/~jocv00/cv02/resume/index.html)

Příjemnou neděli

**Comment by sesm00** [comment]
Dobrý den,
zde je úkol ze cvičení

- [home](https://eso.vse.cz/~sesm00/cv02/)
- [cheatsheet](https://eso.vse.cz/~sesm00/cv02/cheatsheet/)
- [blog](https://eso.vse.cz/~sesm00/cv02/blog/)
- [resume](https://eso.vse.cz/~sesm00/cv02/resume/)

**Comment by Ashley-Unicorn** [comment]
Dobrý den,
odevzdávám úkol z 1. cvičení:

- [Homepage](https://eso.vse.cz/~urvo00/cv02/)
- [Cheatsheet](https://eso.vse.cz/~urvo00/cv02/cheatsheet/)
- [Blog](https://eso.vse.cz/~urvo00/cv02/blog/)
- [Resume](https://eso.vse.cz/~urvo00/cv02/resume/)

**Comment by matj27-vse** [comment]
Dobrý den,
odevzdávám úkol ze cvičení.

- [Homepage](https://eso.vse.cz/~matj27/ukol01/)
- [Cheatsheet](https://eso.vse.cz/~matj27/ukol01/cheatsheet/)
- [Blog](https://eso.vse.cz/~matj27/ukol01/blog/)
- [Resumé](https://eso.vse.cz/~matj27/ukol01/resume/)

**Comment by danoravsky** [comment]
Odkazy na prvni ukol.

https://eso.vse.cz/~orad01/cv02/
https://eso.vse.cz/~orad01/cv02/
https://eso.vse.cz/~orad01/cv02/cheatsheet/
https://eso.vse.cz/~orad01/cv02/blog/
https://eso.vse.cz/~orad01/cv02/resume/

**Comment by Stom19ars** [comment]
Odkazy na první úkol.
Pozn. Trochu jsem nepochopil úkol o blogu tak jsem udělal 2 varianty.

https://eso.vse.cz/~stom19/cv02/
https://eso.vse.cz/~stom19/cv02/cheatsheet/
https://eso.vse.cz/~stom19/cv02/blog1/
https://eso.vse.cz/~stom19/cv02/blog2/
https://eso.vse.cz/~stom19/cv02/resume/

**Comment by nami-kt** [comment]
Dobrý den, odevzdávám svůj domácí úkol CV02:

[Home page](https://eso.vse.cz/~bake01/cv02/)
[Cheatsheet](https://eso.vse.cz/~bake01/cv02/cheatsheet/)
[Resume](https://eso.vse.cz/~bake01/cv02/resume/)
[Blog](https://eso.vse.cz/~bake01/cv02/blog/)

**Comment by 0nmus** [comment]
Dobrý den,

posílám všechny odkazy na první domácí úkol.

https://eso.vse.cz/~muso00/cv02/
https://eso.vse.cz/~muso00/cv02/cheatsheet/
https://eso.vse.cz/~muso00/cv02/blog/
https://eso.vse.cz/~muso00/cv02/resume/

**Comment by janisska** [comment]
Dobrý den,

přikládám odkazy k prvnímu DÚ.

[Rozcestí](https://eso.vse.cz/~stoj10/cv02/)
[Cheatsheet](https://eso.vse.cz/~stoj10/cv02/cheatsheet)
[Blog](https://eso.vse.cz/~stoj10/cv02/blog/)
[Resumé](https://eso.vse.cz/~stoj10/cv02/resume/)

**Comment by m-immer** [comment]
Dobrý den,

zde jsou odkazy na domácí úkol.

[Homepage](https://eso.vse.cz/~immm00/cv02)
[Cheatsheet](https://eso.vse.cz/~immm00/cv02/cheatsheet/)
[Blog](https://eso.vse.cz/~immm00/cv02/blog/)
[Resume](https://eso.vse.cz/~immm00/cv02/resume/)

**Comment by Rollerova** [comment]
Dobrý den,

níže zasílám odkazy na HW01

[Domovská stránka](https://eso.vse.cz/~rolt01/HW01/index.html)
[Cheatsheet](https://eso.vse.cz/~rolt01/HW01/cheatsheet/index.html)
[Blog](https://eso.vse.cz/~rolt01/HW01/blog/index.html)
[Resume](https://eso.vse.cz/~rolt01/HW01/resume/index.html)

**Comment by jan-nejedly** [comment]
Dobrý večer,
také odevzdávám úkol z prvního cvičení.

[Homepage](https://eso.vse.cz/~nejj02/cv02/)
[Cheatsheet](https://eso.vse.cz/~nejj02/cv02/cheatsheet/)
[Blog](https://eso.vse.cz/~nejj02/cv02/blog/)
[Resume](https://eso.vse.cz/~nejj02/cv02/resume/)

**Comment by guliamar** [comment]
dobry vecer, take odevzdavam 1. domaci ukol 

[homepage](https://eso.vse.cz/~gulm04/CV02/index.html)
[cheatsheet](https://eso.vse.cz/~gulm04/CV02/cheatsheet/index.html)
[blog](https://eso.vse.cz/~gulm04/CV02/blog/index.html)
[resume](https://eso.vse.cz/~gulm04/CV02/resume/index.html)

**Comment by Denisprosim** [comment]
Dobrý den, odevzdávám 1. domácí úkol
[https://eso.vse.cz/~misd01/cv02/](url) 
[https://eso.vse.cz/~misd01/cv02/blog](url)
[https://eso.vse.cz/~misd01/cv02/resume](url)
[https://eso.vse.cz/~misd01/cv02/cheatsheet](url)

**Comment by Hoko99** [comment]
Dobré odpoledne,

zde jsou odkazy na 1. DÚ:
[Domovská stránka](https://eso.vse.cz/~kouj10/cv01/)
[Tahák](https://eso.vse.cz/~kouj10/cv01/cheatsheet/)
[Blog](https://eso.vse.cz/~kouj10/cv01/blog/)
[Životopis](https://eso.vse.cz/~kouj10/cv01/resume/)

Koudelka

**Comment by mjamesCZ** [comment]
Dobrý den, odevzdávám první úkol:

[Domů 🏠](https://eso.vse.cz/~slaj26/cv02/)
[Cheatsheet 📓](https://eso.vse.cz/~slaj26/cv02/cheatsheet/)
[Blog 💬](https://eso.vse.cz/~slaj26/cv02/blog/)
[Resume 👨‍💻](https://eso.vse.cz/~slaj26/cv02/resume/)

**Comment by sotonav** [comment]
Dobrý večer,
zde jsou odkazy :)
[Homepage](https://eso.vse.cz/~sotv02/cv02/)
[Cheatsheet](https://eso.vse.cz/~sotv02/cv02/cheatsheet/)
[Blog](https://eso.vse.cz/~sotv02/cv02/blog/)
[Resume](https://eso.vse.cz/~sotv02/cv02/blog/)

**Comment by vanbuncha** [comment]
Odkazy na domací úkol:

[https://eso.vse.cz/~vanv08/cv02/](https://eso.vse.cz/~vanv08/cv02)
[https://eso.vse.cz/~vanv08/cv02/cheatsheet.html](https://eso.vse.cz/~vanv08/cv02/cheatsheet.html)
[https://eso.vse.cz/~vanv08/cv02/blog.html](https://eso.vse.cz/~vanv08/cv02/blog.html)
[https://eso.vse.cz/~vanv08/cv02/resume.html](https://eso.vse.cz/~vanv08/cv02/resume.html)

Děkuji

Nguyen

**Comment by PetrBuk** [comment]
Zdravím, 
odkazy na první úkol:

- [Homepage](https://eso.vse.cz/~bukp00/HW01/)
- [Cheatsheet](https://eso.vse.cz/~bukp00/HW01/cheatsheet/)
- [Životopis](https://eso.vse.cz/~bukp00/HW01/resume/)
- [Blog](https://eso.vse.cz/~bukp00/HW01/blog/)

Krásný den, 
P. Buk

**Comment by prohladno** [comment]
Dobrý den, 
Odkazy na první úkol:
[HOMEPAGE](https://eso.vse.cz/~vlav04/cv02/index.html)
[BLOG](https://eso.vse.cz/~vlav04/cv02/blog/index.html)
[CHEATSHEET](https://eso.vse.cz/~vlav04/cv02/cheatsheet/index.html)
[RESUME](https://eso.vse.cz/~vlav04/cv02/resume/index.html)

**Comment by leglevoj** [comment]
Dobrý den,
odevzdávám domácí úkol cv02:

https://eso.vse.cz/~legv02/cv02/
https://eso.vse.cz/~legv02/cv02/cheatsheet/
https://eso.vse.cz/~legv02/cv02/blog/
https://eso.vse.cz/~legv02/cv02/resume/

**Comment by novakmatej** [comment]
Dobrý den, odevzdávám úkol: 
https://eso.vse.cz/~novm55/cv02/
https://eso.vse.cz/~novm55/cv02/cheatsheet/
https://eso.vse.cz/~novm55/cv02/blog/
https://eso.vse.cz/~novm55/cv02/resume/

**Comment by DariPriadun** [comment]
Dobrý den! odevzdávám domácí úkol:
https://eso.vse.cz/~prid05/cv2/
https://eso.vse.cz/~prid05/cv2/tahak/
https://eso.vse.cz/~prid05/cv2/blog/
https://eso.vse.cz/~prid05/cv2/resume/

**Comment by joskoffel** [comment]
### _Dobrý deň, odovzdávam 1. úkol.:_


- [ ] https://eso.vse.cz/~kolj20/CV2/homepage.html

- [ ] https://eso.vse.cz/~kolj20/CV2/cheatsheet.html

- [ ] https://eso.vse.cz/~kolj20/CV2/blog.html

- [ ] https://eso.vse.cz/~kolj20/CV2/resume.html

xname: kolj20

**Comment by eism00** [comment]
Dobrý den, zde jsou odkazy k prvnímu úkolu : 
https://eso.vse.cz/~eism00/cv02/
https://eso.vse.cz/~eism00/cv02/cheatsheet
https://eso.vse.cz/~eism00/cv02/blog
https://eso.vse.cz/~eism00/cv02/resume

**Comment by Lucissh** [comment]
Dobrý den, zde jsou odkazy k prvnímu úkolu
https://eso.vse.cz/~ngul06/cv02/homepage.html
https://eso.vse.cz/~ngul06/cv02/cheatsheet.html
https://eso.vse.cz/~ngul06/cv02/blog.html
https://eso.vse.cz/~ngul06/cv02/resume.html

**Comment by tominatorcz** [comment]
Dobrý den, posílám odkazy na první domácí úkol:

[https://eso.vse.cz/~mikt04/](Index)
[https://eso.vse.cz/~mikt04/cheatsheet/index.html](Cheatsheet)
[https://eso.vse.cz/~mikt04/blog/index.html](Blog)
[https://eso.vse.cz/~mikt04/resume/index.html](Resume)

**Comment by kosr04** [comment]
Dobrý večer, 
zde jsou odkazy na první domácí úkol:
[https://eso.vse.cz/~kosr04/cv02/](url)
[https://eso.vse.cz/~kosr04/cv02/resume/](url)
[https://eso.vse.cz/~kosr04/cv02/blog/](url)
[https://eso.vse.cz/~kosr04/cv02/cheatsheet/](url)

**Comment by maka090** [comment]
Dobrý večer,
Odevzdávám první úkol
https://eso.vse.cz/~maka09/cv02/
https://eso.vse.cz/~maka09/cv02/cheatsheet/
https://eso.vse.cz/~maka09/cv02/blog/
https://eso.vse.cz/~maka09/cv02/resume/

**Comment by AdnilG** [comment]
Dobrý den,
odevzdávám první domácí úkol:
https://eso.vse.cz/~kunm05/cv02/
https://eso.vse.cz/~kunm05/cv02/cheatsheet/
https://eso.vse.cz/~kunm05/cv02/blog/
https://eso.vse.cz/~kunm05/cv02/resume/

**Comment by mrtomis** [comment]
Dobrý den,
odevzdávám odkazy na první úkol:
https://eso.vse.cz/~trat16/cv02/
https://eso.vse.cz/~trat16/cv02/cheatsheet/
https://eso.vse.cz/~trat16/cv02/blog/
https://eso.vse.cz/~trat16/cv02/resume/

**Comment by tweelare** [comment]
Dobrý den,
odevzdávám první úkol:
https://eso.vse.cz/~kala14/cv02/
https://eso.vse.cz/~kala14/cv02/cheatsheet/
https://eso.vse.cz/~kala14/cv02/blog/
https://eso.vse.cz/~kala14/cv02/resume/

**Comment by annaklonie** [comment]
Dobrý den,

odevzdávám první úkol.

- https://eso.vse.cz/~buit07/cv02/
- https://eso.vse.cz/~buit07/cv02/cheatsheet/
- https://eso.vse.cz/~buit07/cv02/blog/
- https://eso.vse.cz/~buit07/cv02/resume/

**Comment by tarabasek** [comment]
Pěkný večer, úkol k prohlédnutí zde:

- [Rozcestník: ](https://eso.vse.cz/~sirm02/cv02/)
- [Cheatsheet: ](https://eso.vse.cz/~sirm02/cv02/cheatsheet/)
- [Blog: ](https://eso.vse.cz/~sirm02/cv02/blog/)
- [Resume: ](https://eso.vse.cz/~sirm02/cv02/resume/)

**Comment by velflvoj** [comment]
Dobrý den,
odevzdávám první úkol.

https://eso.vse.cz/~velv04/cv02/
https://eso.vse.cz/~velv04/cv02/cheatsheet/
https://eso.vse.cz/~velv04/cv02/resume/
https://eso.vse.cz/~velv04/cv02/blog/

**Comment by vojtechnerad** [comment]
Dobrý večer,
odevzdávám první úkol.

https://eso.vse.cz/~nerv01/cv02/
https://eso.vse.cz/~nerv01/cv02/cheatsheet/
https://eso.vse.cz/~nerv01/cv02/resume/
https://eso.vse.cz/~nerv01/cv02/blog/

**Comment by nvbach91** [comment]
Super, díky všem, na cvičení se podíváme na nejčastější chyby.

**Comment by shaker-jpg** [comment]
Dobrý den, odevzdávám první úkol.
https://eso.vse.cz/~shat07/cv02/home/
https://eso.vse.cz/~shat07/cv02/cheatsheet/
https://eso.vse.cz/~shat07/cv02/blog/
https://eso.vse.cz/~shat07/cv02/resume/
