### ISSUE TITLE
Změna API SP2

### ISSUE THREAD

**Issue by hrubysi** [nvbach91/4IZ268-2021-2022-ZS#97]
Nejde mi upravit již odevzdaný návrh SP2, tak změny sepíšu sem:

Zjistil jsem, že podcast je distribuován z Buzzsprout, tudíž místo Apple API , která není moc vhodná, použiji Buzzsprout API.
Ten ale neobsahuje paginaci a vzhledem k velkému množství dat je nejprve synchronizuji do databáze, na kterou se budu dotazovat skrze vlastní API, které již bude mít i paginaci a vyhledávání.

https://www.buzzsprout.com/api

hrus03

**Comment by nvbach91** [comment]
Ok
